version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0.11
    restart: always
    ports:
      - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=root_pass
     - MYSQL_DATABASE=test_db